# Generated by Django 5.0.1 on 2024-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
