# Generated by Django 5.0.1 on 2024-03-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
